export const nsgConfigs = [
  // NSG for DNS Private Resolver Subnet
  {
    name: "azure-dns-resolver-nsg",
    subnetKeys: ["dns-resolver-inbound-subnet", "dns-resolver-outbound-subnet"],
    tags: { Purpose: "DnsResolverSecurity" },
    rules: [
      {
        name: "AllowDnsFromAWS",
        priority: 100,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "53",
        sourceAddressPrefix: "10.0.0.0/16", // AWS VPC CIDR
        destinationAddressPrefix: "*",
      },
      {
        name: "AllowDnsFromGCP",
        priority: 110,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "53",
        sourceAddressPrefix: "35.199.192.0/19", // GCP Resolver CIDR
        destinationAddressPrefix: "*",
      },
      {
        name: "AllowVnetInBound",
        priority: 120,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "VirtualNetwork",
        destinationAddressPrefix: "VirtualNetwork",
      },
      {
        name: "AllowAzureInfrastructure",
        priority: 130,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "AzureLoadBalancer",
        destinationAddressPrefix: "*",
      },
      {
        name: "DenyAllInbound",
        priority: 4096,
        direction: "Inbound",
        access: "Deny",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "*",
        destinationAddressPrefix: "*",
      },
    ],
  },
  // NSG for Web Subnet
  {
    name: "azure-web-nsg",
    subnetKeys: ["web-subnet"],
    tags: { Purpose: "WebTierSecurity" },
    rules: [
      {
        name: "AllowVnetInBound",
        priority: 100,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "VirtualNetwork",
        destinationAddressPrefix: "VirtualNetwork",
      },
      {
        name: "AllowHttpInbound",
        priority: 150,
        direction: "Inbound",
        access: "Allow",
        protocol: "Tcp",
        sourcePortRange: "*",
        destinationPortRange: "80",
        sourceAddressPrefix: "Internet",
        destinationAddressPrefix: "*",
      },
      {
        name: "AllowHttpsInbound",
        priority: 160,
        direction: "Inbound",
        access: "Allow",
        protocol: "Tcp",
        sourcePortRange: "*",
        destinationPortRange: "443",
        sourceAddressPrefix: "Internet",
        destinationAddressPrefix: "*",
      },
      {
        name: "AllowSshFromBastion",
        priority: 200,
        direction: "Inbound",
        access: "Allow",
        protocol: "Tcp",
        sourcePortRange: "*",
        destinationPortRange: "22",
        sourceAddressPrefix: "10.2.110.0/24", // Bastion Subnet CIDR
        destinationAddressPrefix: "*",
      },
      {
        name: "DenyAllInbound",
        priority: 4096,
        direction: "Inbound",
        access: "Deny",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "*",
        destinationAddressPrefix: "*",
      },
    ],
  },
  // NSG for App Subnet
  {
    name: "azure-app-nsg",
    subnetKeys: ["app-subnet"],
    tags: { Purpose: "AppTierSecurity" },
    rules: [
      {
        name: "AllowVnetInBound",
        priority: 100,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "VirtualNetwork",
        destinationAddressPrefix: "VirtualNetwork",
      },
      {
        name: "AllowAzureLoadBalancerInBound",
        priority: 101,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "AzureLoadBalancer",
        destinationAddressPrefix: "*",
      },
      {
        name: "AllowSshFromBastion",
        priority: 200,
        direction: "Inbound",
        access: "Allow",
        protocol: "Tcp",
        sourcePortRange: "*",
        destinationPortRange: "22",
        sourceAddressPrefix: "10.2.110.0/24", // Bastion Subnet CIDR
        destinationAddressPrefix: "*",
      },
      {
        name: "DenyAllInbound",
        priority: 4096,
        direction: "Inbound",
        access: "Deny",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "*",
        destinationAddressPrefix: "*",
      },
    ],
  },
  // NSG for DB MySQL Subnet
  {
    name: "azure-db-mysql-nsg",
    subnetKeys: ["db-mysql-subnet"],
    tags: { Purpose: "DatabaseSecurity" },
    rules: [
      {
        name: "AllowVnetInBound",
        priority: 100,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "VirtualNetwork",
        destinationAddressPrefix: "VirtualNetwork",
      },
      // {
      //   name: "AllowMysqlFromApp",
      //   priority: 160,
      //   direction: "Inbound",
      //   access: "Allow",
      //   protocol: "Tcp",
      //   sourcePortRange: "*",
      //   destinationPortRange: "3306",
      //   sourceAddressPrefix: "10.2.20.0/24", // App Subnet CIDR
      //   destinationAddressPrefix: "*",
      // },
      {
        name: "DenyAllInbound",
        priority: 4096,
        direction: "Inbound",
        access: "Deny",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "*",
        destinationAddressPrefix: "*",
      },
    ],
  },
  // NSG for DB PostgreSQL Subnet
  {
    name: "azure-db-postgres-nsg",
    subnetKeys: ["db-postgres-subnet"],
    tags: { Purpose: "DatabaseSecurity" },
    rules: [
      {
        name: "AllowVnetInBound",
        priority: 100,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "VirtualNetwork",
        destinationAddressPrefix: "VirtualNetwork",
      },
      {
        name: "DenyAllInbound",
        priority: 4096,
        direction: "Inbound",
        access: "Deny",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "*",
        destinationAddressPrefix: "*",
      },
    ],
  },
  // NSG for Storage Subnet (Azure Files Private Endpoint)
  {
    name: "azure-storage-nsg",
    subnetKeys: ["storage-subnet"],
    tags: { Purpose: "StorageSecurity" },
    rules: [
      {
        name: "AllowNFSFromAWS",
        priority: 100,
        direction: "Inbound",
        access: "Allow",
        protocol: "Tcp",
        sourcePortRange: "*",
        destinationPortRange: "2049",
        sourceAddressPrefix: "10.0.0.0/16", // AWS VPC CIDR
        destinationAddressPrefix: "*",
      },
      {
        name: "AllowNFSFromGCP",
        priority: 110,
        direction: "Inbound",
        access: "Allow",
        protocol: "Tcp",
        sourcePortRange: "*",
        destinationPortRange: "2049",
        sourceAddressPrefix: "10.1.0.0/16", // GCP VPC CIDR
        destinationAddressPrefix: "*",
      },
      {
        name: "AllowVnetInBound",
        priority: 120,
        direction: "Inbound",
        access: "Allow",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "VirtualNetwork",
        destinationAddressPrefix: "VirtualNetwork",
      },
      {
        name: "DenyAllInbound",
        priority: 4096,
        direction: "Inbound",
        access: "Deny",
        protocol: "*",
        sourcePortRange: "*",
        destinationPortRange: "*",
        sourceAddressPrefix: "*",
        destinationAddressPrefix: "*",
      },
    ],
  },
  {
    name: "azure-appgw-nsg",
    subnetKeys: ["web-appgw-subnet"],
    tags: { Purpose: "AppGatewaySecurity" },
    rules: [
      {
        name: "AllowGatewayManagerInbound",
        priority: 100,
        direction: "Inbound",
        access: "Allow",
        protocol: "Tcp",
        sourcePortRange: "*",
        destinationPortRange: "65200-65535",
        sourceAddressPrefix: "GatewayManager",
        destinationAddressPrefix: "*",
      },
      {
        name: "AllowHGwttpInbound",
        priority: 110,
        direction: "Inbound",
        access: "Allow",
        protocol: "Tcp",
        sourcePortRange: "*",
        destinationPortRange: "80",
        sourceAddressPrefix: "Internet",
        destinationAddressPrefix: "*",
      },
      {
        name: "AllowHGwttpsInbound",
        priority: 120,
        direction: "Inbound",
        access: "Allow",
        protocol: "Tcp",
        sourcePortRange: "*",
        destinationPortRange: "443",
        sourceAddressPrefix: "Internet",
        destinationAddressPrefix: "*",
      },
    ],
  },
];
